name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  sqflite: ^2.4.3
  path: ^1.9.1
  path_provider: ^2.1.6
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3
  flutter_html: ^3.0.0
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.4
  build_runner: ^2.15.1

flutter:
  uses-material-design: true
  assets:
    - assets/
