name: prompter_mj
description: Use this CLI application to create multiple choice or binary-type questions.
version: 1.0.1
repository: https://github.com/mjhabib/Flutter_Remake_Angela.Yu_Stephen.Grider_Hussain.Mustafa/tree/main/day_30_dart_prompter

environment:
  sdk: ^3.12.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
